global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert.rules"

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: golang
    metrics_path: /metrics
    static_configs:
      - targets:
          - golang:9000
  - job_name: nodeexporter
    scrape_interval: 5s
    static_configs:
      - targets: ["nodeexporter:9500"]
